### ISSUE TITLE
failed to run custom build command for `librocksdb-sys v5.14.3`

### ISSUE THREAD

**Issue by jamesray1** [paritytech/shasper#48]
```bash
[jray@jr-dl shasper]$ cargo run -- --dev
   Compiling librocksdb-sys v5.14.3
   Compiling substrate-network v0.1.0 (https://github.com/paritytech/substrate#60801d8b)
   Compiling substrate-basic-authorship v0.1.0 (https://github.com/paritytech/substrate#60801d8b)
   Compiling substrate-consensus-aura-slots v0.1.0 (https://github.com/paritytech/substrate#60801d8b)
error: failed to run custom build command for `librocksdb-sys v5.14.3`
process didn't exit successfully: `/home/jray/shasper/target/debug/build/librocksdb-sys-7204a4f39962fc8b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
[jray@jr-dl shasper]$ echo $LIBCLANG_PATH

[jray@jr-dl shasper]$ RUST_BACKTRACE=1 cargo run -- --dev
   Compiling librocksdb-sys v5.14.3
   Compiling shasper-runtime v0.9.0 (/home/jray/shasper/runtime)
   Compiling substrate-rpc v0.1.0 (https://github.com/paritytech/substrate#60801d8b)
error: failed to run custom build command for `librocksdb-sys v5.14.3`
process didn't exit successfully: `/home/jray/shasper/target/debug/build/librocksdb-sys-7204a4f39962fc8b/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/result.rs:835
  10: core::ops::function::FnOnce::call_once
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1664
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:238
  11: <lazy_static::lazy::Lazy<T>>::get::{{closure}}
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:28
  12: std::sync::once::Once::call_once::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sync/once.rs:230
  13: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:397
  14: std::sync::once::Once::call_once
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sync/once.rs:230
  15: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:27
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/<::lazy_static::__lazy_static_internal macros>:12
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/<::lazy_static::__lazy_static_internal macros>:13
  16: bindgen::ensure_libclang_is_loaded
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1671
  17: bindgen::Bindings::generate
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1686
  18: bindgen::Builder::generate
             at /home/jray/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.43.2/src/lib.rs:1216
  19: build_script_build::bindgen_rocksdb
             at ./build.rs:34
  20: build_script_build::main
             at ./build.rs:287
  21: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  24: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  25: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  26: main
  27: __libc_start_main
  28: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Which path should I set LIBCLANG_PATH to, or how can this be done automatically?

Should I cross-post an issue with librocksdb-sys?

**Comment by lz931585538** [comment]
Hello，I have the same problem as you.
error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `D:\code\Rust\openethereum-master\target\debug\build\librocksdb-sys-2cf4461ebc7f7d64\build-script-build` (exit code: 0x80000003)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
rocksdb/include/rocksdb/c.h:45:9: warning: #pragma once in main file, err: false

And I had already installed clang  like this.

clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-w64-windows-gnu
Thread model: posix

But the same error is reported when I run the program.


And other question

Microsoft Visual C++ Runtime Library

Assertion failed!

**Comment by lxj-my** [comment]
I also encounter such difficulty， @jamesray1 given the answer 
ubuntu: 
sudo apt  -y  install  clang
sudo apt  -y  install  gcc
sudo apt  -y  install  cmake

**Comment by lz931585538** [comment]
> I also encounter such difficulty， @jamesray1 given the answer
> ubuntu:
> sudo apt -y install clang
> sudo apt -y install gcc
> sudo apt -y install cmake

I had already installed clang,gcc,cmake on windows.
But the same error is reported when I run the program.

**Comment by lz931585538** [comment]
> I also encounter such difficulty， @jamesray1 given the answer
> ubuntu:
> sudo apt -y install clang
> sudo apt -y install gcc
> sudo apt -y install cmake

Now I got this error:
Microsoft Visual C++ Runtime Library

Assertion failed!

Program:C:\Prigram Files\LLVM\bin\libclang.dll
File:D:\src\llvm_release_build_3.7.0\llvm\tools\cla.../Type.h
Line:5591

Expression:isa<T>(CanonicalType)

For information on how your program can cause an assertion failure,see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enable)

**Comment by lz931585538** [comment]
> Hello，I have the same problem as you.
> error: failed to run custom build command for `librocksdb-sys v6.6.4`
> 
> Caused by:
> process didn't exit successfully: `D:\code\Rust\openethereum-master\target\debug\build\librocksdb-sys-2cf4461ebc7f7d64\build-script-build` (exit code: 0x80000003)
> --- stdout
> cargo:rerun-if-changed=build.rs
> cargo:rerun-if-changed=rocksdb/
> cargo:rerun-if-changed=snappy/
> cargo:rerun-if-changed=lz4/
> cargo:rerun-if-changed=zstd/
> cargo:rerun-if-changed=zlib/
> cargo:rerun-if-changed=bzip2/
> cargo:warning=couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
> cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
> 
> --- stderr
> rocksdb/include/rocksdb/c.h:45:9: warning: #pragma once in main file, err: false
> 
> And I had already installed clang like this.
> 
> clang version 3.7.0 (tags/RELEASE_370/final)
> Target: x86_64-w64-windows-gnu
> Thread model: posix
> 
> But the same error is reported when I run the program.
> 
> And other question
> 
> Microsoft Visual C++ Runtime Library
> 
> Assertion failed!

Got this error !

Microsoft Visual C++ Runtime Library

Assertion failed!

Program:C:\Prigram Files\LLVM\bin\libclang.dll
File:D:\src\llvm_release_build_3.7.0\llvm\tools\cla.../Type.h
Line:5591

Expression:isa<T>(CanonicalType)

For information on how your program can cause an assertion failure,see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enable)

**Comment by Carlos9986** [comment]
I also encounter such difficulty， @jamesray1 given the answer
ubuntu:
u need to install clang, gcc, cmake, llvm.

**Comment by JBA-Khalifa** [comment]
Install openssl-devel, it might work.

**Comment by gnubrasil** [comment]
fedora 33
sudo dnf install clang
sudo dnf install gcc
sudo dnf install cmake

**Comment by przemek64** [comment]
> fedora 33
> sudo dnf install clang
> sudo dnf install gcc
> sudo dnf install cmake

Worked for me. Thanks

**Comment by pranavmahadeokar** [comment]
if  windows user download ubuntu cli from microsoft store  them WSL for windows now you are set.

sudo dnf install clang
sudo dnf install gcc
sudo dnf install cmake
